"""
Tests for the synthetic-demonstration endpoints. Run from the repository root:

    .venv\\Scripts\\python.exe -m unittest backend.tests.test_synthetic -v

They read outputs/synthetic/context/ (generated by scripts/synthetic/run_pipeline.py) and check that every
served value equals the generated file, that ranges are sane, and that the NYC-only explorer is closed
under the synthetic profile. If the context outputs have not been generated the tests are skipped.
"""
import json
import unittest
from pathlib import Path
from unittest import mock

import pandas as pd
from fastapi.testclient import TestClient

from backend import config
from backend.main import app

CTX = Path(config.PROJECT_ROOT) / "outputs" / "synthetic" / "context"


@unittest.skipUnless((CTX / "overview.json").exists(), "synthetic context outputs not generated")
class SyntheticEndpointTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.patches = [mock.patch.object(config, "CONTEXT_DIR", CTX), mock.patch.object(config, "IS_SYNTHETIC", True)]
        for p in cls.patches:
            p.start()
        cls.ctx = TestClient(app)
        cls.client = cls.ctx.__enter__()

    @classmethod
    def tearDownClass(cls):
        cls.ctx.__exit__(None, None, None)
        for p in cls.patches:
            p.stop()

    def test_overview_matches_files(self):
        j = self.client.get("/api/synthetic/overview").json()
        disk = json.loads((CTX / "overview.json").read_text())
        self.assertEqual(j["kpis"], disk)
        wards = pd.read_csv(CTX / "ward_summary.csv")
        self.assertEqual(j["kpis"]["population_covered"], int(wards["population"].sum()))
        self.assertIn("Synthetic", j["label"])

    def test_wards_filter_and_ranges(self):
        j = self.client.get("/api/synthetic/wards", params={"city": "Mysuru"}).json()
        self.assertGreater(j["count"], 0)
        self.assertTrue(all(w["city"] == "Mysuru" for w in j["items"]))
        allw = self.client.get("/api/synthetic/wards").json()["items"]
        for w in allw:
            self.assertGreater(w["population"], 0)
            self.assertTrue(0 <= w["vulnerable_pop_share"] <= 1)
            if w["risk_score"] is not None:
                self.assertTrue(0 <= w["risk_score"] <= 100)

    def test_prioritization_sorted_and_actions(self):
        j = self.client.get("/api/synthetic/prioritization", params={"page_size": 50}).json()
        scores = [i["priority_score"] for i in j["items"]]
        self.assertEqual(scores, sorted(scores, reverse=True))
        self.assertEqual([i["rank"] for i in j["items"]], list(range(1, len(scores) + 1)))
        repair = self.client.get("/api/synthetic/prioritization", params={"action": "Repair now", "page_size": 100}).json()
        plan = pd.read_csv(CTX.parent / "optimal_dispatch_plan.csv")
        self.assertEqual(repair["total"], int(plan["selected_for_repair"].sum()))

    def test_causal_matches_stage11_file_and_truth_check(self):
        j = self.client.get("/api/synthetic/causal").json()
        est = pd.read_csv(CTX.parent / "displacement_estimates.csv").set_index("effect_name")
        for e in j["estimates"]:
            self.assertAlmostEqual(e["estimate"], est.loc[e["effect"], "estimate"], places=9)
        chk = j.get("planted_effect_check")
        if chk:
            self.assertTrue(chk["ci_contains_truth"])

    def test_risk_model_has_no_outcome_features(self):
        j = self.client.get("/api/synthetic/risk-model").json()
        for f in j["features"]:
            self.assertNotIn("duration", f)
            self.assertNotIn("closed", f)
            self.assertNotIn("dark_night", f)
        self.assertGreater(j["top_decile_capture"], j["no_skill_top_decile_capture"])

    def test_scenarios(self):
        j = self.client.get("/api/synthetic/scenarios").json()
        self.assertEqual(j["selected"], "baseline")
        names = {s["scenario"] for s in j["scenarios"]}
        self.assertTrue({"baseline", "high_rainfall", "high_density", "poor_infrastructure", "improved_intervention"} <= names)
        stress = self.client.get("/api/synthetic/scenarios", params={"scenario": "high_density"}).json()
        fifo = next(p for p in stress["policies"] if p["policy"].startswith("FIFO"))
        ex = next(p for p in stress["policies"] if p["policy"] == "Causal priority, ex-ante")
        self.assertLess(ex["benchmark_extra_crimes"], fifo["benchmark_extra_crimes"])
        self.assertTrue(next(p for p in stress["policies"] if "Stage 12" in p["policy"])["uses_hindsight"])

    def test_nyc_only_explorer_closed(self):
        self.assertEqual(self.client.get("/api/operations/capacity").status_code, 404)
        self.assertEqual(self.client.get("/api/evidence/stage11").status_code, 404)

    def test_methodology_traceability_endpoints_exist(self):
        j = self.client.get("/api/synthetic/methodology").json()
        paths = set(app.openapi()["paths"])
        for row in j["traceability"]:
            for ep in row["endpoint"].split(","):
                self.assertIn(ep.strip(), paths, ep)


if __name__ == "__main__":
    unittest.main()
