/** Shapes of the /api/profile and /api/synthetic/* responses (all values are generated by the pipeline). */
export interface Profile {
  profile: string;
  synthetic: boolean;
  synthetic_label: string | null;
  region: string;
  map_center: [number, number];
  map_zoom: number;
  boroughs: string[];
  context_available: boolean;
  notice: string;
}

export interface SynKpis {
  population_covered: number; wards: number; cities: number; outages_cleaned: number; outages_scored: number;
  high_risk_wards: number; high_medium_priority_outages: number; high_priority_outages: number;
  repairs_recommended_per_day: number; daily_repair_capacity_k: number; tau_effect: string; tau_value: number;
  priority_improvement_day30_pct: number | null; predicted_impact_priority_points_day30: number | null;
  fifo_impact_priority_points_day30: number | null; benchmark_vs_fifo_pct_baseline: number | null;
  benchmark_vs_fifo_pct_stress: number | null; data_period: [string, string];
}
export interface SynOverview {
  available: boolean; message?: string; label: string; kpis: SynKpis;
  risk_model: { spearman_predicted_vs_observed: number; top_decile_capture: number; top_decile_lift: number };
}

export interface Ward {
  ward_id: string; city: string; latitude: number; longitude: number; area_class: string; population: number;
  pop_density_per_km2: number; income_index: number; vulnerable_pop_share: number; rainfall_mm_year: number;
  elevation_m: number; slope_pct: number; dist_main_road_km: number; dist_depot_km: number; pole_age_years: number;
  outages: number; night_crimes: number; scored_outages: number | null; mean_outage_days: number | null;
  mean_local_crime_rate: number | null; mean_predicted_risk: number | null; mean_priority_score: number | null;
  max_priority_score: number | null; high_medium_priority: number; repair_now: number; outages_per_10k_pop: number;
  outages_per_km2: number; night_crimes_per_km2: number; risk_score: number | null; risk_category: string;
}
export interface WardsResponse { available: boolean; count: number; items: Ward[] }

export interface PopRow {
  group: string; wards: number; population: number; outages: number; outages_per_10k_pop: number;
  night_crimes_per_km2: number; mean_predicted_risk: number | null; mean_priority_score: number | null;
  mean_outage_days: number | null; high_medium_priority: number; repair_now: number;
}
export interface PopulationResponse { available: boolean; groups: Record<string, PopRow[]> }

export interface Relation { label: string; x: string; y: string; n_wards: number; spearman: number }
export interface RelationshipsResponse { available: boolean; relations: Relation[]; points: Record<string, number | string>[] }

export interface CausalEffect {
  effect: string; estimate: number; se: number | null; ci_lower: number | null; ci_upper: number | null;
  p_value: number | null; ring: string; n_pairs: number;
}
export interface SynCausal {
  available: boolean; estimates: CausalEffect[]; estimator: string;
  naive_before_after: { description: string; mean_change: number; se: number; n_pairs: number };
  matched_did_direct_during: { description: string; mean: number; se_unclustered: number };
  tau_used_for_priority: { effect: string; value: number };
  effect_by_density: { group: string; n_pairs: number; estimate: number; se_unclustered: number; planted_truth?: number }[];
  planted_effect_check?: {
    purpose: string; expected_direct_effect_in_matched_sample: number; estimated_direct_during: number;
    estimated_ci: [number, number]; ci_contains_truth: boolean; n_matched_treated_with_truth: number;
  };
  reading_guide: { prediction: string; causal: string };
}

export interface RiskModel {
  available: boolean; model: string; target: string; validation: string; n_outages: number; features: string[];
  spearman_predicted_vs_observed: number; poisson_deviance_explained: number; top_decile_capture: number;
  top_decile_lift: number; no_skill_top_decile_capture: number; interpretation: string;
  feature_importance: { feature: string; importance: number }[];
}

export interface PrioItem {
  rank: number; unique_key: number; ward_id: string; city: string; area_class: string; created_date: string;
  duration_days: number; population: number; pop_density_per_km2: number; local_crime_rate: number | null;
  predicted_risk: number; risk_percentile: number; priority_score: number; priority_tier: string;
  recommended_action: string; optimization_rank: number | null;
}
export interface PrioResponse { available: boolean; total: number; page: number; page_size: number; sorted_by: string; items: PrioItem[]; note: string }

export interface PolicyRow {
  policy: string; uses_hindsight: boolean; capacity_k_per_day: number; outages: number; mean_wait_days: number;
  p90_wait_days: number; priority_weighted_wait_days: number; benchmark_extra_crimes: number | null;
  benchmark_vs_fifo_pct: number | null; benchmark_vs_fifo_abs: number | null;
}
export interface ScenarioResponse {
  available: boolean; selected: string; notes: string[];
  scenarios: { scenario: string; scenario_label: string; scenario_description: string; capacity_k_per_day: number; outages: number }[];
  policies: PolicyRow[];
}

export interface TraceRow { ui_metric: string; endpoint: string; file: string; source: string }
export interface Methodology {
  available: boolean; label: string; why_synthetic: string; simulated: string[]; assumed_relationships: string[];
  model_derived: string[]; synthetic_values: string[]; limitations: string[]; data_period: [string, string] | null;
  traceability: TraceRow[];
}
